### ISSUE TITLE
CUDA error: out of memory

### ISSUE THREAD

**Issue by Rudychan** [jfzhang95/pytorch-deeplab-xception#72]
My GPU is 1080Ti and the memory is 12GB.
when I train in resnet/drn backbone , the problem raise soon within 10 seconds. ):
Training parameters  are from 'train_voc.sh'  .

**Comment by Davidchangyuanhan** [comment]
make the batch-size smaller

**Comment by duanyongli** [comment]
I encounter the same problem. Have you solved it?

**Comment by Rudychan** [comment]
> I encounter the same problem. Have you solved it?

yep，just set the batch size = 2, problem solved.

**Comment by duanyongli** [comment]
> > I encounter the same problem. Have you solved it?
> 
> yep，just set the batch size = 2, problem solved.

thanks.
